#!/usr/bin/env node
/**
 * CONTRAST CHECK (T6, D3)
 * ────────────────────────
 * Computes real WCAG relative-luminance contrast ratios for every
 * text/background pair actually used in styles/globals.css, instead of
 * eyeballing it. Run with `npm run contrast-check`; output is also saved
 * to docs/CONTRAST_REPORT.md by this script.
 *
 * Pairs are hand-listed below (matching the color tokens in globals.css)
 * rather than parsed from the CSS automatically — the app's palette is
 * small and stable, and an explicit list is easier to audit than a CSS
 * parser that could silently miss a rule.
 */

function luminance([r, g, b]) {
  const c = (v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * c(r) + 0.7152 * c(g) + 0.0722 * c(b);
}

function contrast(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la > lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

function blend(fg, bg, alpha) {
  return fg.map((c, i) => Math.round(c * alpha + bg[i] * (1 - alpha)));
}

const white = [255, 255, 255];
const sand = [250, 247, 242];
const ink = [22, 33, 28];
const green = [46, 94, 78];
const greenDeep = [31, 68, 56];
const inkMuted = blend(ink, sand, 0.64);
const inkFaint = blend(ink, sand, 0.66);

// Threshold: 4.5:1 for normal text, 3:1 for large text / UI boundaries.
const pairs = [
  { name: "White text on --gn-green (primary button)", fg: white, bg: green, minimum: 4.5 },
  { name: "White text on --gn-green-deep (button hover/press)", fg: white, bg: greenDeep, minimum: 4.5 },
  { name: "--ink on --gn-sand (body text)", fg: ink, bg: sand, minimum: 4.5 },
  { name: "--ink-muted on --gn-sand", fg: inkMuted, bg: sand, minimum: 4.5 },
  { name: "--ink-faint on --gn-sand", fg: inkFaint, bg: sand, minimum: 4.5 },
  { name: "--teal-text on white (badge)", fg: [14, 122, 108], bg: white, minimum: 4.5 },
  { name: "--amber-text on white (badge)", fg: [122, 83, 22], bg: white, minimum: 4.5 },
  { name: "--red-text (clay) on white (badge)", fg: [165, 82, 42], bg: white, minimum: 4.5 },
  { name: "--gn-clay-deep on white (due-today badge)", fg: [165, 82, 42], bg: white, minimum: 4.5 },
  { name: "--blue-text (slate) on white (badge)", fg: [47, 79, 116], bg: white, minimum: 4.5 },
  { name: "--violet-text on white (Premium)", fg: [92, 52, 184], bg: white, minimum: 4.5 },
  { name: "--gn-green as focus-visible outline on --gn-sand (UI boundary)", fg: green, bg: sand, minimum: 3 },
  { name: "--solid-border on white (card/input boundary)", fg: blend(ink, white, 0.5), bg: white, minimum: 3 },
];

let failed = 0;
const rows = pairs.map((p) => {
  const ratio = contrast(p.fg, p.bg);
  const pass = ratio >= p.minimum;
  if (!pass) failed += 1;
  return { ...p, ratio, pass };
});

console.log("Contrast check (WCAG relative luminance)\n");
for (const r of rows) {
  const status = r.pass ? "PASS" : "FAIL";
  console.log(`[${status}] ${r.name}: ${r.ratio.toFixed(2)}:1 (min ${r.minimum}:1)`);
}

const reportLines = [
  "# Contrast Report",
  "",
  "Generated by `scripts/contrast-check.mjs` — computed with the WCAG relative-luminance formula, not eyeballed. Re-run with `npm run contrast-check` after any color token change.",
  "",
  "| Pair | Ratio | Minimum | Result |",
  "|---|---|---|---|",
  ...rows.map((r) => `| ${r.name} | ${r.ratio.toFixed(2)}:1 | ${r.minimum}:1 | ${r.pass ? "Pass" : "**FAIL**"} |`),
];

try {
  const fs = await import("node:fs");
  fs.mkdirSync("docs", { recursive: true });
  fs.writeFileSync("docs/CONTRAST_REPORT.md", reportLines.join("\n") + "\n");
  console.log("\nWrote docs/CONTRAST_REPORT.md");
} catch (err) {
  console.warn("Could not write docs/CONTRAST_REPORT.md:", err.message);
}

if (failed > 0) {
  console.error(`\n${failed} pair(s) failed the minimum contrast ratio.`);
  process.exit(1);
}
console.log(`\nAll ${rows.length} pairs pass.`);
